var searchData=
[
  ['virtualized_20cluster',['Virtualized Cluster',['../guide-virtualizedcluster.html',1,'']]],
  ['validateproperties',['validateProperties',['../classwrench_1_1_bare_metal_compute_service.html#a199bba66e56383b91125026715bde9cf',1,'wrench::BareMetalComputeService::validateProperties()'],['../classwrench_1_1_cloud_service.html#af2d39456e9526ef63d077b76166fa1da',1,'wrench::CloudService::validateProperties()']]],
  ['virtualizedclusterservice',['VirtualizedClusterService',['../classwrench_1_1_virtualized_cluster_service.html',1,'wrench::VirtualizedClusterService'],['../classwrench_1_1_virtualized_cluster_service.html#a7be5224d65410f4570ce9f9e9c835bd5',1,'wrench::VirtualizedClusterService::VirtualizedClusterService()']]],
  ['virtualizedclusterservicemessage',['VirtualizedClusterServiceMessage',['../classwrench_1_1_virtualized_cluster_service_message.html',1,'wrench::VirtualizedClusterServiceMessage'],['../classwrench_1_1_virtualized_cluster_service_message.html#a124699b0def3ecd4bd91f9ea90991471',1,'wrench::VirtualizedClusterServiceMessage::VirtualizedClusterServiceMessage()']]],
  ['virtualizedclusterservicemessagepayload',['VirtualizedClusterServiceMessagePayload',['../classwrench_1_1_virtualized_cluster_service_message_payload.html',1,'wrench']]],
  ['virtualizedclusterservicemigratevmanswermessage',['VirtualizedClusterServiceMigrateVMAnswerMessage',['../classwrench_1_1_virtualized_cluster_service_migrate_v_m_answer_message.html',1,'wrench::VirtualizedClusterServiceMigrateVMAnswerMessage'],['../classwrench_1_1_virtualized_cluster_service_migrate_v_m_answer_message.html#a8a24158ba2ee9494765dc4008a9f4d83',1,'wrench::VirtualizedClusterServiceMigrateVMAnswerMessage::VirtualizedClusterServiceMigrateVMAnswerMessage()']]],
  ['virtualizedclusterservicemigratevmrequestmessage',['VirtualizedClusterServiceMigrateVMRequestMessage',['../classwrench_1_1_virtualized_cluster_service_migrate_v_m_request_message.html',1,'wrench::VirtualizedClusterServiceMigrateVMRequestMessage'],['../classwrench_1_1_virtualized_cluster_service_migrate_v_m_request_message.html#a96267f06eb76fff7ca50a4fd58fc6aae',1,'wrench::VirtualizedClusterServiceMigrateVMRequestMessage::VirtualizedClusterServiceMigrateVMRequestMessage()']]],
  ['virtualizedclusterserviceproperty',['VirtualizedClusterServiceProperty',['../classwrench_1_1_virtualized_cluster_service_property.html',1,'wrench']]],
  ['vm_5fboot_5foverhead_5fin_5fseconds',['VM_BOOT_OVERHEAD_IN_SECONDS',['../classwrench_1_1_cloud_service_property.html#a7e2fddc7f539dedff89fb41635a5b200',1,'wrench::CloudServiceProperty']]],
  ['vm_5fhostname',['vm_hostname',['../classwrench_1_1_cloud_service_create_v_m_request_message.html#ad4fb06a93a8ceb82ababe1f342b2d701',1,'wrench::CloudServiceCreateVMRequestMessage::vm_hostname()'],['../classwrench_1_1_cloud_service_shutdown_v_m_request_message.html#a8c7a69388cd9451095a2e1aa96dc4fdb',1,'wrench::CloudServiceShutdownVMRequestMessage::vm_hostname()'],['../classwrench_1_1_cloud_service_start_v_m_request_message.html#aefd63dd24deca7f6940db2c006d07557',1,'wrench::CloudServiceStartVMRequestMessage::vm_hostname()'],['../classwrench_1_1_cloud_service_suspend_v_m_request_message.html#afe8e071668d420d40e83a21e2472d788',1,'wrench::CloudServiceSuspendVMRequestMessage::vm_hostname()'],['../classwrench_1_1_cloud_service_resume_v_m_request_message.html#a77975278481b99f13380266ebf77f294',1,'wrench::CloudServiceResumeVMRequestMessage::vm_hostname()'],['../classwrench_1_1_virtualized_cluster_service_migrate_v_m_request_message.html#ace7cf886213ce713432360e68ed9f494',1,'wrench::VirtualizedClusterServiceMigrateVMRequestMessage::vm_hostname()']]],
  ['vm_5flist',['vm_list',['../classwrench_1_1_cloud_service.html#a41782dd4332c11a992997562132f35e1',1,'wrench::CloudService']]]
];
