var searchData=
[
  ['validateproperties_987',['validateProperties',['../classwrench_1_1_cloud_compute_service.html#a63fc712f096052e4cd7971e83bb3ca70',1,'wrench::CloudComputeService']]],
  ['vertex_5ft_988',['vertex_t',['../namespacewrench.html#a1a7c1e68889eb42acd45ca4cc224bbdd',1,'wrench']]],
  ['vertexproperties_989',['VertexProperties',['../structwrench_1_1_vertex_properties.html',1,'wrench']]],
  ['virtualizedclustercomputeservice_990',['VirtualizedClusterComputeService',['../classwrench_1_1_virtualized_cluster_compute_service.html',1,'wrench::VirtualizedClusterComputeService'],['../classwrench_1_1_virtualized_cluster_compute_service.html#a40a78b7e0efc2fc8bdd40196cb380b49',1,'wrench::VirtualizedClusterComputeService::VirtualizedClusterComputeService()']]],
  ['virtualizedclustercomputeservicemessage_991',['VirtualizedClusterComputeServiceMessage',['../classwrench_1_1_virtualized_cluster_compute_service_message.html',1,'wrench::VirtualizedClusterComputeServiceMessage'],['../classwrench_1_1_virtualized_cluster_compute_service_message.html#a4f5802c712db9eaf0c26a9255b293e9f',1,'wrench::VirtualizedClusterComputeServiceMessage::VirtualizedClusterComputeServiceMessage()']]],
  ['virtualizedclustercomputeservicemessagepayload_992',['VirtualizedClusterComputeServiceMessagePayload',['../classwrench_1_1_virtualized_cluster_compute_service_message_payload.html',1,'wrench']]],
  ['virtualizedclustercomputeservicemigratevmanswermessage_993',['VirtualizedClusterComputeServiceMigrateVMAnswerMessage',['../classwrench_1_1_virtualized_cluster_compute_service_migrate_v_m_answer_message.html',1,'wrench::VirtualizedClusterComputeServiceMigrateVMAnswerMessage'],['../classwrench_1_1_virtualized_cluster_compute_service_migrate_v_m_answer_message.html#a7eabf58f6601737740ee565fc58c3c1e',1,'wrench::VirtualizedClusterComputeServiceMigrateVMAnswerMessage::VirtualizedClusterComputeServiceMigrateVMAnswerMessage()']]],
  ['virtualizedclustercomputeservicemigratevmrequestmessage_994',['VirtualizedClusterComputeServiceMigrateVMRequestMessage',['../classwrench_1_1_virtualized_cluster_compute_service_migrate_v_m_request_message.html',1,'wrench::VirtualizedClusterComputeServiceMigrateVMRequestMessage'],['../classwrench_1_1_virtualized_cluster_compute_service_migrate_v_m_request_message.html#a386da75034daee991ab9298e715c48aa',1,'wrench::VirtualizedClusterComputeServiceMigrateVMRequestMessage::VirtualizedClusterComputeServiceMigrateVMRequestMessage()']]],
  ['virtualizedclustercomputeserviceproperty_995',['VirtualizedClusterComputeServiceProperty',['../classwrench_1_1_virtualized_cluster_compute_service_property.html',1,'wrench']]],
  ['vm_5fboot_5foverhead_5fin_5fseconds_996',['VM_BOOT_OVERHEAD_IN_SECONDS',['../classwrench_1_1_cloud_compute_service_property.html#abe4ada614f43f5d8cc5cfbbeaaaa21f0',1,'wrench::CloudComputeServiceProperty']]],
  ['vm_5flist_997',['vm_list',['../classwrench_1_1_cloud_compute_service.html#a9cc6528d46f1f65b249ed16452f1e587',1,'wrench::CloudComputeService']]],
  ['vm_5fname_998',['vm_name',['../classwrench_1_1_cloud_compute_service_create_v_m_answer_message.html#a5ba3aedc34e79b4736afea532fc988b4',1,'wrench::CloudComputeServiceCreateVMAnswerMessage::vm_name()'],['../classwrench_1_1_cloud_compute_service_shutdown_v_m_request_message.html#a70be6202e7c725594e14407ccee162b7',1,'wrench::CloudComputeServiceShutdownVMRequestMessage::vm_name()'],['../classwrench_1_1_cloud_compute_service_start_v_m_request_message.html#a28c2dfb747909dce505465a2ad1798fb',1,'wrench::CloudComputeServiceStartVMRequestMessage::vm_name()'],['../classwrench_1_1_cloud_compute_service_suspend_v_m_request_message.html#aa8ed4b1f26ab3a8cf1084c3308e0ce72',1,'wrench::CloudComputeServiceSuspendVMRequestMessage::vm_name()'],['../classwrench_1_1_cloud_compute_service_resume_v_m_request_message.html#ac352d039e057d7a48af7d51b2faaf082',1,'wrench::CloudComputeServiceResumeVMRequestMessage::vm_name()'],['../classwrench_1_1_cloud_compute_service_destroy_v_m_request_message.html#a7bf075917aef27e6dc7a2b47db5976d1',1,'wrench::CloudComputeServiceDestroyVMRequestMessage::vm_name()'],['../classwrench_1_1_virtualized_cluster_compute_service_migrate_v_m_request_message.html#a3a782b475c6fb16583bd7c1bd4dd8a54',1,'wrench::VirtualizedClusterComputeServiceMigrateVMRequestMessage::vm_name()']]],
  ['vm_5fresource_5fallocation_5falgorithm_999',['VM_RESOURCE_ALLOCATION_ALGORITHM',['../classwrench_1_1_cloud_compute_service_property.html#afb10f34e1cf1714393bd451e52de926c',1,'wrench::CloudComputeServiceProperty']]],
  ['vm_5fto_5fpm_5fmap_1000',['vm_to_pm_map',['../classwrench_1_1_s4_u___virtual_machine.html#a507fc58f74806774cc25c8e47c14dd60',1,'wrench::S4U_VirtualMachine']]]
];
