var searchData=
[
  ['checkdeferredstart',['checkDeferredStart',['../classwrench_1_1_w_m_s.html#ac264b461c6f5900b96a1c9e33f7f4d58',1,'wrench::WMS']]],
  ['cloudcomputeservice',['CloudComputeService',['../classwrench_1_1_cloud_compute_service.html#ad4a6ef48539aaa658dd5942188db2b48',1,'wrench::CloudComputeService']]],
  ['compute',['compute',['../classwrench_1_1_simulation.html#a26092a37ea422703f0880748844cf820',1,'wrench::Simulation']]],
  ['createdatamovementmanager',['createDataMovementManager',['../classwrench_1_1_w_m_s.html#aaf8902aadfd0542509cd0cae5519bcf3',1,'wrench::WMS']]],
  ['createenergymeter',['createEnergyMeter',['../classwrench_1_1_w_m_s.html#a5fc42a94aca690011863e8883008bbf0',1,'wrench::WMS::createEnergyMeter(const std::map&lt; std::string, double &gt; &amp;measurement_periods)'],['../classwrench_1_1_w_m_s.html#a1b5edd90a9783a2eaa846a561f165fe0',1,'wrench::WMS::createEnergyMeter(const std::vector&lt; std::string &gt; &amp;hostnames, double measurement_period)']]],
  ['createjobmanager',['createJobManager',['../classwrench_1_1_w_m_s.html#a3f1a1451efda2a41d2d96a41cf229698',1,'wrench::WMS']]],
  ['createpilotjob',['createPilotJob',['../classwrench_1_1_job_manager.html#a9ef786306730359866e3fd2bd3aadaf7',1,'wrench::JobManager']]],
  ['createstandardjob',['createStandardJob',['../classwrench_1_1_job_manager.html#a7dbe3dd72fcfbe0198690bfaa802ed9a',1,'wrench::JobManager::createStandardJob(std::vector&lt; WorkflowTask *&gt; tasks, std::map&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt; &gt; file_locations, std::vector&lt; std::tuple&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt;, std::shared_ptr&lt; FileLocation &gt; &gt;&gt; pre_file_copies, std::vector&lt; std::tuple&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt;, std::shared_ptr&lt; FileLocation &gt; &gt;&gt; post_file_copies, std::vector&lt; std::tuple&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt; &gt;&gt; cleanup_file_deletions)'],['../classwrench_1_1_job_manager.html#a225888e00f01dc43a8279314c135282c',1,'wrench::JobManager::createStandardJob(std::vector&lt; WorkflowTask *&gt; tasks, std::map&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt; &gt; file_locations)'],['../classwrench_1_1_job_manager.html#a9ae187056244f02a1e0445f75ee40b4a',1,'wrench::JobManager::createStandardJob(WorkflowTask *task, std::map&lt; WorkflowFile *, std::shared_ptr&lt; FileLocation &gt; &gt; file_locations)']]],
  ['createvm',['createVM',['../classwrench_1_1_cloud_compute_service.html#a12b81ccd09bbaa0c48351c13cf116e3e',1,'wrench::CloudComputeService::createVM(unsigned long num_cores, double ram_memory, std::map&lt; std::string, std::string &gt; property_list={}, std::map&lt; std::string, double &gt; messagepayload_list={})'],['../classwrench_1_1_cloud_compute_service.html#a532d53afc282c73425d4928c104f2763',1,'wrench::CloudComputeService::createVM(unsigned long num_cores, double ram_memory, std::string desired_vm_name, std::map&lt; std::string, std::string &gt; property_list={}, std::map&lt; std::string, double &gt; messagepayload_list={})']]]
];
